name: Deploy to WebLogic

on:
  push: 
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug Environment
        run: |
          echo "Current directory:"
          pwd
          echo "List files:"
          ls -l
          echo "App folder:"
          ls -l app

      - name: Copy WAR to WebLogic Container
        run: |
          docker cp ./app/hello-world.war weblogic1411:/u01/oracle/hello-world.war

      - name: Copy WLST Script
        run: |
          docker cp ./wlst/deploy.py weblogic1411:/u01/oracle/deploy.py

      - name: Execute WLST Deployment
        run: |
          docker exec weblogic1411 bash -c "/u01/oracle/oracle_common/common/bin/wlst.sh /u01/oracle/deploy.py"

      - name: Check
        run: |
          curl -f http://172.17.0.2:7001/hello-world
